source = ~/.config/mango/cfg/autostart.conf
source = ~/.config/mango/cfg/monitor.conf
source = ~/.config/mango/cfg/input.conf
source = ~/.config/mango/cfg/environment.conf
source = ~/.config/mango/cfg/visuals.conf
source = ~/.config/mango/cfg/misc.conf
source = ~/.config/mango/cfg/binds.conf
source = ~/.config/mango/cfg/rules.conf
